# Generated by Django 2.2 on 2020-11-03 12:51

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='enter_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='grade',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='self_introduction',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='skill',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
