# Generated by Django 2.2 on 2020-11-03 08:35

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(max_length=10, null=True)),
                ('enter_time', models.DateTimeField()),
                ('grade', models.CharField(max_length=5)),
                ('skill', models.CharField(max_length=50)),
                ('self_introduction', ckeditor_uploader.fields.RichTextUploadingField()),
                ('teacher', models.ForeignKey(default='00000', on_delete=django.db.models.deletion.DO_NOTHING, to='user.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=10)),
                ('school', models.CharField(max_length=10)),
                ('enter_time', models.DateTimeField()),
                ('grade', models.CharField(max_length=5)),
                ('help', models.CharField(max_length=50)),
                ('self_introduction', ckeditor_uploader.fields.RichTextUploadingField()),
                ('student_No', models.ForeignKey(default='00000', on_delete=django.db.models.deletion.DO_NOTHING, to='user.Profile')),
            ],
        ),
    ]
