# Generated by Django 2.2 on 2020-11-03 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20201103_1953'),
    ]

    operations = [
    ]
