# Generated by Django 2.2 on 2020-11-03 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_teacher_teacher_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='teacher_Profile',
        ),
    ]
