# Generated by Django 2.2 on 2020-11-03 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20201103_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='enter_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
