# Generated by Django 2.2 on 2020-11-04 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20201104_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='enter_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
