# Generated by Django 2.2 on 2020-11-04 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20201104_1739'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='grade',
        ),
        migrations.AddField(
            model_name='profile',
            name='grade',
            field=models.CharField(default='大一', max_length=5),
            preserve_default=False,
        ),
    ]
