# Generated by Django 2.2 on 2020-11-04 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20201104_1746'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='grade',
        ),
    ]
