# Generated by Django 2.2 on 2020-11-02 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(max_length=10, null=True)),
                ('enter_time', models.DateTimeField()),
                ('grade', models.CharField(max_length=5)),
                ('skill', models.CharField(max_length=50)),
                ('self_introduction', models.CharField(max_length=50)),
                ('teacher_No', models.ForeignKey(default='00000', on_delete=django.db.models.deletion.DO_NOTHING, to='user.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=10)),
                ('school', models.CharField(max_length=10)),
                ('enter_time', models.DateTimeField()),
                ('grade', models.CharField(max_length=5)),
                ('help', models.CharField(max_length=50)),
                ('self_introduction', models.CharField(max_length=50)),
                ('student_No', models.ForeignKey(default='00000', on_delete=django.db.models.deletion.DO_NOTHING, to='user.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('SID', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Apprenticeship.Student')),
                ('TID', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Apprenticeship.Teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=100)),
                ('relationship_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Apprenticeship.Relationship')),
            ],
        ),
        migrations.CreateModel(
            name='Critic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=100)),
                ('homework_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Apprenticeship.Homework')),
            ],
        ),
    ]
