# Generated by Django 2.2 on 2020-10-28 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Sex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(max_length=10)),
                ('school', models.CharField(max_length=10)),
                ('enter_time', models.DateTimeField()),
                ('grade', models.CharField(max_length=5)),
                ('skill', models.CharField(max_length=50)),
                ('self_introduction', models.CharField(max_length=50)),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Apprenticeship.Major')),
                ('teacher_sex', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Apprenticeship.Sex')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=10)),
                ('school', models.CharField(max_length=10)),
                ('enter_time', models.DateTimeField()),
                ('grade', models.CharField(max_length=5)),
                ('help', models.CharField(max_length=50)),
                ('self_introduction', models.CharField(max_length=50)),
                ('major', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Apprenticeship.Major')),
                ('student_sex', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Apprenticeship.Sex')),
            ],
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('SID', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Apprenticeship.Student')),
                ('TID', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Apprenticeship.Teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=100)),
                ('relationship_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Apprenticeship.Relationship')),
            ],
        ),
        migrations.CreateModel(
            name='Critic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=100)),
                ('homework_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Apprenticeship.Homework')),
            ],
        ),
    ]
