# Generated by Django 2.2 on 2020-11-03 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Apprenticeship', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='teacher_No',
        ),
        migrations.AlterField(
            model_name='relationship',
            name='SID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.Student'),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='TID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.Teacher'),
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
