# Generated by Django 2.2 on 2020-11-01 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20201101_1938'),
        ('Apprenticeship', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='major',
        ),
        migrations.RemoveField(
            model_name='student',
            name='student_sex',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='major',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='school',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='teacher_name',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='teacher_sex',
        ),
        migrations.AddField(
            model_name='student',
            name='student_No',
            field=models.ForeignKey(default='00000', on_delete=django.db.models.deletion.DO_NOTHING, to='user.Profile'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='teacher_No',
            field=models.ForeignKey(default='00000', on_delete=django.db.models.deletion.DO_NOTHING, to='user.Profile'),
        ),
        migrations.DeleteModel(
            name='Major',
        ),
        migrations.DeleteModel(
            name='Sex',
        ),
    ]
