# Generated by Django 2.2 on 2020-11-02 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Apprenticeship', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='teacher_No',
            new_name='teacher',
        ),
    ]
