# Generated by Django 2.2 on 2020-11-02 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apprenticeship', '0002_auto_20201101_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='teacher_name',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
