# Generated by Django 2.2 on 2020-11-02 14:14

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Apprenticeship', '0002_auto_20201102_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='self_introduction',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='self_introduction',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
