# Generated by Django 2.2 on 2020-11-25 08:06

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0014_readnum_user'),
        ('Apprenticeship', '0003_request'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Request',
            new_name='ApprenticeRequest',
        ),
    ]
