# Generated by Django 2.2 on 2020-11-03 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Apprenticeship', '0003_auto_20201102_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relationship',
            name='TID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.Teacher'),
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
